/*
 * generated by Xtext 2.12.0
 */
package org.xtext

import org.eclipse.emf.ecore.EPackage;

import com.google.inject.Injector;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class UpctformaevaluaStandaloneSetup extends UpctformaevaluaStandaloneSetupGenerated {

	def static void doSetup() {
		new UpctformaevaluaStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
